### ISSUE TITLE
Perform a repository level registration

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Aloha#1]
In the **participants** folder create a new text file (.txt) with the file name being your roll number <roll-number>.txt (eg- iit2020157.txt, iec2020080.txt). In the .txt file write your details as follows

Name:
Roll Number:
Discord ID:
Tech Parent:
Favorite Society:

**Comment by DISHASONI99** [comment]
> In the **participants** folder create a new text file (.txt) with the file name being your roll number .txt (eg- iit2020157.txt, iec2020080.txt). In the .txt file write your details as follows
> 
> Name: Roll Number: Discord ID: Tech Parent: Favorite Society:

where is the participant folder , not able to find it sir

**Comment by pankaj1707k** [comment]
![image](https://user-images.githubusercontent.com/76695979/209067502-0470af35-6945-462a-adc4-3a570dba6427.png)
